version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  mysqldb:
    image: mysql:latest
    container_name: mysqldb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    depends_on:
      - rabbitmq

  eurekaserver:
    build: ./eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    depends_on:
      - rabbitmq

  configserver:
    build: ./configserver
    container_name: configserver
    ports:
      - "9999:9999"
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    depends_on:
      - rabbitmq

  animal-ms:
    build: ./animal-microservice
    container_name: animal-ms
    ports:
      - "8082:8082"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - eurekaserver
      - configserver
      - rabbitmq

  animal-ms2:
    build: ./animal-microservice
    container_name: animal-ms2
    ports:
      - "8084:8082"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - eurekaserver
      - configserver
      - rabbitmq

  gatewayserver:
    build: ./gatewayserver
    container_name: gatewayserver
    ports:
      - "8888:8888"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - eurekaserver
      - rabbitmq

  groupe-ms:
    build: ./groupe-microservice
    container_name: groupe-ms
    ports:
      - "8081:8081"
    environment:
      - DISCOVERY_SERVICE_URL=http://eurekaserver:8761/eureka
      - CONFIG_SERVICE_URL=http://configserver:9999
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - eurekaserver
      - configserver
      - rabbitmq
